[build]
  command = "npm run build"
  publish = ".next"

[dev]
  framework = "next"
  port = 8888       # This is the port for the Netlify Dev proxy
  targetPort = 3000 # This is the port where Next.js is actually running